[versions]
minecraft = "1.20.4-R0.1-SNAPSHOT"
googlejavaformat = "1.17.0"
[plugins]
userdev = { id = "io.papermc.paperweight.userdev", version = "1.7.7" }
runpaper = { id = "xyz.jpenilla.run-paper", version = "2.3.1" }
shadow = { id = "com.gradleup.shadow", version = "8.3.6" }
lombok = { id = "io.freefair.lombok", version = "8.13" }
paperyml = { id = "net.minecrell.plugin-yml.paper", version = "0.6.0" }
spotless = { id = "com.diffplug.spotless", version = "6.25.0" }
hangar = { id = "io.papermc.hangar-publish-plugin", version = "0.1.2" }
minotaur = { id = "com.modrinth.minotaur", version = "2.8.7" }
[libraries]
annotations = { module = "org.jetbrains:annotations", version = "24.1.0" }
guice = { module = "com.google.inject:guice", version = "7.0.0" }
luckperms = { module = "net.luckperms:api", version = "5.4" }
bstats = { module = "org.bstats:bstats-bukkit", version = "3.1.0" }
classgraph = { module = "io.github.classgraph:classgraph", version = "4.8.179" }