name: Testing

on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - run: chmod +x gradlew
      - name: Build project
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.1.1'
          arguments: build